// config.bin - 14:43:37 09/01/14, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

class CfgPatches {
	class Koninklijke_Landmacht {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F_BLUFOR"};
	};
};
class CfgFactionClasses
{
	class Koninklijke_Landmacht
	{
		displayName="Koninklijke Landmacht";
		icon="\Koninklijke Landmacht Units\Icon\Icon.jpg";
		priority=100;
		side=1;
	};
};
class CfgVehicleClasses
{
	class Cars_Desert
	{
		displayName="Cars Desert";
	};

};

class CfgVehicles {
	class MRAP_03_base_F;	// External class reference
	
	class Fennek_Desert : MRAP_03_base_F {
		author = "Stafford";
		scope = public;
		displayName = "Fennek";
		side = TWest;
		vehicleClass = "Cars_Desert";
		faction = Koninklijke_Landmacht;
		crew = "KL_Desert_GL";
		typicalCargo[] = {"KL_Desert_GL"};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\soft_f_beta\MRAP_03\Data\mrap_03_ext_co.paa", "\a3\data_f\vehicles\turret_co.paa"};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
		
		class TransportMagazines
		{
			class _xx_1Rnd_HE_Grenade_shell
			{
				magazine="1Rnd_HE_Grenade_shell";
				count=100;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=100;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=100;
			};
			class _xx_SmokeShellGreen
			{
				magazine="SmokeShellGreen";
				count=50;
			};
			class _xx_30Rnd_65x39_caseless_mag
			{
				magazine="30Rnd_65x39_caseless_mag";
				count=100;
			};
			class _xx_100Rnd_65x39_caseless_mag
			{
				magazine="100Rnd_65x39_caseless_mag";
				count=100;
			};
		};
		class TransportWeapons {};
	};
	class MRAP_03_hmg_base_F;	// External class reference
	
	class Fennek_Desert_HMG : MRAP_03_hmg_base_F {
		author = "Diesel";
		scope = public;
		displayName = "Fennek HMG";
		side = TWest;
		vehicleClass = "Cars_Desert";
		faction = Koninklijke_Landmacht;
		crew = "KL_Desert_GL";
		typicalCargo[] = {"KL_Desert_GL"};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\soft_f_beta\MRAP_03\Data\mrap_03_ext_co.paa", "\a3\data_f\vehicles\turret_co.paa"};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
		
		class TransportMagazines
		{
			class _xx_1Rnd_HE_Grenade_shell
			{
				magazine="1Rnd_HE_Grenade_shell";
				count=100;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=100;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=100;
			};
			class _xx_SmokeShellGreen
			{
				magazine="SmokeShellGreen";
				count=50;
			};
			class _xx_30Rnd_65x39_caseless_mag
			{
				magazine="30Rnd_65x39_caseless_mag";
				count=100;
			};
			class _xx_100Rnd_65x39_caseless_mag
			{
				magazine="100Rnd_65x39_caseless_mag";
				count=100;
			};
		};
		
		class TransportWeapons {};
	};
	class MRAP_03_gmg_base_F;	// External class reference
	
	class Fennek_Desert_GMG : MRAP_03_gmg_base_F {
		author = "Diesel";
		scope = public;
		displayName = "Fennek GMG";
		side = TWest;
		vehicleClass = "Cars_Desert";
		faction = Koninklijke_Landmacht;
		crew = "KL_Desert_GL";
		typicalCargo[] = {"KL_Desert_GL"};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\soft_f_beta\MRAP_03\Data\mrap_03_ext_co.paa", "\a3\data_f\vehicles\turret_co.paa"};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
		
		class TransportMagazines
		{
			class _xx_1Rnd_HE_Grenade_shell
			{
				magazine="1Rnd_HE_Grenade_shell";
				count=100;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=100;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=100;
			};
			class _xx_SmokeShellGreen
			{
				magazine="SmokeShellGreen";
				count=50;
			};
			class _xx_30Rnd_65x39_caseless_mag
			{
				magazine="30Rnd_65x39_caseless_mag";
				count=100;
			};
			class _xx_100Rnd_65x39_caseless_mag
			{
				magazine="100Rnd_65x39_caseless_mag";
				count=100;
			};
		};
		class TransportWeapons {};
	};
};
